export const COACH_ENGINE_CONFIG = {
  windowDays: 21,
  minEligibleDays: 17,
  minWeighIns: 10,
  recentImportBlockDays: 7,
  keepBandPercentPerWeek: 0.15,
  maintainKeepBandPercentPerWeek: 0.1,
  mediumAdjustmentThreshold: 0.35,
  lightAdjustmentCalories: 100,
  heavyAdjustmentCalories: 150,
  loseDailyDeficitCalories: 500,
  gainDailySurplusCalories: 300,
  calorieFloor: 1200,
  adherence: {
    maxCalorieDeviationPercent: 10,
    minProteinHitRate: 85,
    minStepAdherencePercent: 90,
    minCardioAdherencePercent: 90,
  },
  explicitConfounderLookbackDays: 7,
  scoreWeights: {
    intakeCoverage: 40,
    weighIns: 25,
    explicitStates: 10,
    interventionStability: 10,
    dataHygiene: 15,
  },
  scoreCaps: {
    recoveryIssue: 25,
    recentImport: 40,
    partialDays: 49,
    interventionChange: 74,
    unmarkedLoggedDays: 74,
    explicitConfounders: 74,
  },
  confidenceBands: {
    none: 24,
    low: 49,
    medium: 74,
  },
} as const
